### ISSUE TITLE
Bug: no way to exit idalogue

### ISSUE THREAD

**Issue by fireglow** [Zeg9/minetest-protect#5]
There's a bug:
Once opened, there is no way to exit the dialogue to add new permitted players, short of a logout.

**Comment by justtestrestoration** [comment]
isn't it enough to just hit the escape key? on minetest game engine 0.4.14 I don't get any problems. On what system are you and have you tried running it using the 0.4.14 game engine of minetest?

**Comment by fireglow** [comment]
I've switched all my servers over to tenplus1's version of this mod a week after posting this.
The problem was very real and persistent then, the project seemed (and apparently still is) abandoned.
This can probably be closed.
